export const category = [
    { key: 'Erythrocytes', val: { name: "Erythrocytes", symbol: "Tpt/l", value:"", low: 3.9, high: 6.2 }, info: [{title: 'What\'s Erythrocytes?', img: 'Blood/Erythrocytes-1.jpg', desc: 'Red blood cells, or erythrocytes, are the most common kind of blood cell. They carry oxygen from your lungs throughout your body and are shaped like doughnuts, with a central protein called hemoglobin that binds with oxygen.'}, {title: 'Did you know?', img: '', desc: ''}] },
    { key: 'Hematocrit', val: { name: "Hematocrit", symbol: "%", value:"47.32", low: 33.0, high: 49.0 }, info: [{title: 'What\'s Hematocrit?', img: 'Blood/Hematocrit-1.jpg', desc: 'Hematocrit is the percentage of red blood cells in your blood. It indicates how dense the blood is.'}, {title: 'Did you know?', img: '', desc: ''}] },
    { key: 'Hemoglobin', val: { name: "Hemoglobin", symbol: "g/dl", value:"16.9", low: 12.0, high: 18.0 }, info: [{title: 'What\'s Hemoglobin?', img: 'Blood/Hemoglobin-1.jpg', desc: 'Hemoglobin is a protein in red blood cells that carries oxygen from lungs to muscles, brain, digestive system and all other parts of your body. It\'s what makes your blood red.'}, {title: 'Did you know?', img: '', desc: ''}] },
    { key: 'Iron', val: { name: "Iron", symbol: "µmol/l", value:"17.30", low: 9.0, high: 31.0 }, info: [{title: 'What\'s Iron?', img: 'Blood/Iron-1.jpg', desc: 'Iron is a mineral that occurs naturally in foods and is important for making red blood cells. It\'s a main component of the red blood pigment hemoglobin, which helps your body transport oxygen from your lungs to the rest of the body.'}, {title: 'Did you know?', img: '', desc: ''}] },
    { key: 'MCH', val: { name: "MCH", symbol: "pg", value:"27.9", low: 28.0, high: 33.0 }, info: [{title: 'What\'s MCH?', img: 'Blood/MCH-1.jpg', desc: 'Mean corpuscular hemoglobin, or MCH, is a measurement of the average quantity of hemoglobin in each of your red blood cells. Hemoglobin is necessary for the efficient transport of oxygen through your bloodstream.'}, {title: 'Did you know?', img: '', desc: ''}] },
    { key: 'MCHC', val: { name: "MCHC", symbol: "g/dl", value:"31", low: 33.0, high: 36.0 }, info: [{title: 'MWhat\'s CHC?', img: 'Blood/MCHC-1.jpg', desc: 'MCHC, or mean corpuscular hemoglobin concentration, is the average concentration of hemoglobin found in your red blood cell. It\'s calculated by dividing hemoglobin by hematocrit.'}, {title: 'Did you know?', img: '', desc: ''}] },
    { key: 'MCV', val: { name: "MCV", symbol: "fl", value:"90.1", low: 80.0, high: 99.0 }, info: [{title: 'What\'s MCV?', img: 'Blood/MCV-1.jpg', desc: 'MCV stands for mean corpuscular volume, which is a measurement of the size of your red blood cells. They carry oxygen through your blood.'}, {title: 'Did you know?', img: '', desc: ''}] },
    { key: 'Thrombocytes', val: { name: "Thrombocytes", symbol: "Gpt/l", value:"", low: 150.0, high: 370.0 }, info: [{title: 'What\'s Thrombocytes?', img: 'Blood/Thrombocytes-1.jpg', desc: 'Thrombocytes, or platelets, are the part of your blood that help with clotting. When you get cut, platelets cluster at your wound to stop the bleeding, acting as a natural bandage.'}, {title: 'Did you know?', img: '', desc: ''}] },
    { key: 'Cholestrol', val: { name: "Cholestrol", symbol: "mmol/l", value:"14.27", low: 0, high: 5.2 }, info: [{title: 'What\'s Cholestrol?', img: 'Heart/ch-1.jpg', desc: 'Cholesterol is a waxy, fat-like substance and produced in your liver. It\'s vital to produce hormones like estrogen, testosterone, and vitamin D, and helps you digest foods.'}, {title: '', img: '', desc: " "}] },
    { key: 'HDL cholestrol', val: { name: "HDL cholestrol", symbol: "mmol/l", value:"2.94", low: 1.03, high: 3.3 }, info: [{title: 'What\'s HDL Cholestrol?', img: 'Heart/Hdl-Ch-1.jpg', desc: " High-density lipoprotein (HDL), often called 'good' cholesterol, is a big part of your body's lipid transport system. It helps remove excess cholesterol from your body, keeps blood vessels clear and the heart healthy."}, {title: '', img: '', desc: " "}] },
    { key: 'LDH', val: { name: "LDH", symbol: "µkat/l", value:"", low: 0, high: 4.13 }, info: [{title: 'What\'s LDH?', img: 'Heart/Ldh-1.jpg', desc: " Lactate dehydrogenase (LDH) is an enzyme that helps to break down glucose in your muscles. It's present in almost all your body tissues, and released in case of cell damage. This makes it a marker for muscle and heart muscle injury."}, {title: '', img: '', desc: " "}] },
    { key: 'LDL cholestrol', val: { name: "LDL cholestrol", symbol: "mmol/l", value:"10.55", low: 0, high: 4.0 }, info: [{title: 'What\'s LDL cholestrol?', img: 'Heart/Ldl-ch-1.jpg', desc: " Low-density lipoprotein (LDL) carries cholesterol from your liver to the cells and circulates in your blood. It's often referred to as bad cholesterol, but some levels are important for your health."}, {title: '', img: '', desc: " "}] },
    { key: 'LDL HDL ratio', val: { name: "LDL/HDL ratio", symbol: "Quotient", value:"3.6", low: 0, high: 3.5 }, info: [{title: 'What\'s LDL/HDL ratio?', img: 'Heart/Ldl-Hdl-R-1.jpg', desc: " The LDL/HDL ratio is a measure of the amount of bad cholesterol (LDL) and good cholesterol (HDL) in your bloodstream. It's calculated by dividing your total LDL by your total HDL."}, {title: '', img: '', desc: " "}] },
    { key: 'Non-HDL cholestrol', val: { name: "Non-HDL cholestrol", symbol: "mmol/l", value:"11.35", low: 0, high: 3.9 }, info: [{title: 'What\'s Non-HDL cholestrol?', img: 'Heart/Non-Hdl-ch-1.jpg', desc: "Non-HDL cholesterol is a way of measuring how much bad cholesterol is in your blood. It is calculated by subtracting HDL (good) cholesterol from the total amount of cholesterol. "}, {title: '', img: '', desc: " "}] },
    { key: 'Triglycerides', val: { name: "Triglycerides", symbol: "mmol/l", value:"7.7", low: 0, high: 8.3 }, info: [{title: 'What\'s Triglycerides?', img: 'Heart/Tr-1.jpg', desc: "Triglycerides are a type of fat in your blood, and the main storage form of fatty acids in your body. They're stored in your liver and muscle tissue as energy for when you need it. They are also known as blood fats. "}, {img: '', desc: " "}] },
    { key: 'TSH', val: { name: "TSH", symbol: "mIU/l", value:"1.39", low: 0.2, high: 5.3 }, info: [{title: 'What\'s TSH?', img: 'Hormones/Tsh-1.jpg', desc: "Thyroid-stimulating hormone (TSH) is a hormone that helps regulate your thyroid gland, which affects how your body functions. If it's not working properly, it can cause problems like fatigue, hair loss, weight gain or depression. "}, {title: '', img: '', desc: " "}] },
    { key: 'Basophils', val: { name: "Basophils %", symbol: "%", value:"0.5", low: 0.0, high: 1.0 }, info: [{title: 'What\'s Basophils?', img: 'Immunity/Bs-1.jpg', desc: " Basophils are white blood cells that play a key role in allergic reactions and release chemicals that cause swelling and inflammation. The basophil percentage describes their amount relative to all white blood cells in the sample."}, {title: '', img: '', desc: " "}] },
    { key: 'Basophils absolute', val: { name: "Basophils absolute", symbol: "Gpt/l", value:"0.04", low: 0.0, high: 0.2 }, info: [{title: 'What\'s Basophils absolute?', img: 'Immunity/BSA-1.jpg', desc: "Basophils are white blood cells that play a key role in allergic reactions and release chemicals that cause swelling and inflammation. The absolute basophil count describes the number of basophils in a blood sample. "}, {title: '', img: '', desc: " "}] },
    { key: 'Eosinophils', val: { name: "Eosinophils %", symbol: "%", value:"2.8", low: 2.0, high: 4.0 }, info: [{title: 'What\'s Eosinophils?', img: 'Immunity/Eo-1.jpg', desc: "Eosinophils are white blood cells that help protect against infections. They circulate through your body, ingesting bacteria, fungi, and other invaders. The percentage describes their amount relative to all white blood cells. "}, {title: '', img: '', desc: " "}] },
    { key: 'Eosinophils absolute', val: { name: "Eosinophils absolute", symbol: "Gpt/l", value:"0.22", low: 0.02, high: 0.75 }, info: [{title: 'What\'s Eosinophils absolute?', img: 'Immunity/EoA-1.jpg', desc: "Eosinophils are white blood cells that help protect against infections. They circulate through your body, ingesting bacteria, fungi, and other invaders. The absolute count is the number of eosinophils per microliter of blood. "}, {title: '', img: '', desc: " "}] },
    { key: 'IgG', val: { name: "IgG", symbol: "g/l", value:"", low: 5.4, high: 18.22 }, info: [{title: 'What\'s IgG?', img: 'Immunity/IgG-1.jpg', desc: " Immunoglobulin G (IgG) is the most common antibody in your body. It helps your immune system fight bacteria, viruses, and fungi. IgG provides long-term immunity and can last for years after infection with a virus or bacteria."}, {title: '', img: '', desc: " "}] },
    { key: 'Leukocytes', val: { name: "Leukocytes", symbol: "Gpt/l", value:"7.78", low: 3.9, high: 10.2 }, info: [{title: 'What\'s Leukocytes?', img: 'Immunity/Le-1.jpg', desc: " White blood cells, or leukocytes, are the defenders of your body. They help your immune system fight off infection and promote healing. Their primary role is to protect the body from foreign invaders such as bacteria or viruses."}, {title: '', img: '', desc: " "}] },
    { key: 'Lymphocytes', val: { name: "Lymphocytes %", symbol: "%", value:"40.5", low: 20.0, high: 45.0 }, info: [{title: 'What\'s Lymphocytes?', img: 'Immunity/Ly-1.jpg', desc: "Lymphocytes are white blood cells that lead a specific immune response part of a larger group including monocytes, B-cells, and T-cells. The lymphocytes % refers to how many of all your white blood cells are lymphocytes. "}, {title: '', img: '', desc: " "}] },
    { key: 'Lymphocytes absolute', val: { name: "Lymphocytes absolute", symbol: "Gpt/l", value:"3.15", low: 1.1, high: 4.5 }, info: [{title: 'What\'s Lymphocytes absolute?', img: 'Immunity/LyA-1.jpg', desc: " Lymphocytes are white blood cells that lead a specific immune response - part of a larger group including monocytes, B-cells, and T-cells. The lymphocytes % refers to how many of all your white blood cells are lymphocytes."}, {title: '', img: '', desc: " "}] },
    { key: 'Monocytes', val: { name: "Monocytes %", symbol: "%", value:"3.6", low: 4.0, high: 12.0 }, info: [{title: 'What\'s Monocytes?', img: 'Immunity/Mo-1.jpg', desc: " Monocytes are white blood cells that fight infection. They clean up old tissue and bacteria and help repair damaged tissue. The percentage of monocytes describes the proportion of total white blood cells that are monocytes."}, {title: '', img: '', desc: " "}] },
    { key: 'Monocytes absolute', val: { name: "Monocytes absolute", symbol: "Gpt/l", value:"0.28", low: 0.1, high: 0.9 }, info: [{title: 'What\'s Monocytes absolute?', img: 'Immunity/MoA-1.jpg', desc: "Monocytes are white blood cells that fight infection. They clean up old tissue and bacteria and help repair damaged tissue. The absolute monocyte count is a measure of the number of these type of white blood cells in your blood. "}, {title: '', img: '', desc: " "}] },
    { key: 'Neutrophils', val: { name: "Neutrophils %", symbol: "%", value:"52.3", low: 42.0, high: 77.0 }, info: [{title: 'What\'s Neutrophils?', img: 'Immunity/Ne-1.jpg', desc: " Neutrophils are the most abundant type of white blood cells. They fight bacteria and other foreign invaders. The percentage of neutrophils refers to how many of your white blood cells are neutrophils."}, {title: '', img: '', desc: " "}] },
    { key: 'Neutrophils absolute', val: { name: "Neutrophils absolute", symbol: "Gpt/l", value:"4.06", low: 1.5, high: 7.7 }, info: [{title: 'What\'s Neutrophils absolute?', img: 'Immunity/NeA-1.jpg', desc: "Neutrophils are the most abundant type of white blood cells. They fight bacteria and other foreign invaders. The absolute neutrophil count identifies how many neutrophils are in a sample of your blood. "}, {title: '', img: '', desc: " "}] },
    { key: 'SARS-CoV-2-IgG quant', val: { name: "SARS-CoV-2-IgG quant", symbol: "AU/mL", value:"", low: 0.4, high: 250 }, info: [{title: 'What\'s SARS-CoV-2-IgG quant?', img: 'Immunity/Saras-1.jpg', desc: "SARS-CoV-2-IgG is an antibody that recognizes the SARS coronavirus. This test shows whether your body has been in contact with some form of the virus in the past through either infection or vaccination. "}, {title: '', img: '', desc: " "}] },
    { key: 'Total protien', val: { name: "Total protien", symbol: "g/l", value:"73", low: 60.0, high: 80.0 }, info: [{title: 'What\'s Total protien?', img: 'Immunity/Tp-1.jpg', desc: "Total protein (TP) is a measure of the amount of protein in your blood. These proteins are a key component of your cell function, repair, and growth. They also play a role in blood clotting, immune defense, and hormone production. "}, {title: '', img: '', desc: " "}] },
    { key: 'Apolipoprotien-A1(APO-A1)', val: { name: "Apolipoprotien - A1 (APO-A1)", symbol: "mg/dl", value:"122", low: 86.0, high: 152.0 }, info: [{title: '', img: '', desc: " "}, {title: '', img: '', desc: " "}] },
    { key: 'Apolipoprotien-B(APO-B)', val: { name: "Apolipoprotien - B (APO-B)", symbol: "mg/dl", value:"102", low: 56.0, high: 145.0 }, info: [{title: '', img: '', desc: " "}, {title: '', img: '', desc: " "}] },
    { key: 'APO B APO A1 Ratio (APO B A1)', val: { name: "APO B / APO A1 Ratio (APO B/A1)", symbol: "Ratio", value:"0.8", low: 0.40, high: 1.26 }, info: [{title: '', img: '', desc: " "}, {title: '', img: '', desc: " "}] },
    { key: 'Creatinine', val: { name: "Creatinine", symbol: "mg/dl", value:"0.76", low: 0, high: 1.16 }, info: [{title: 'What\'s Creatinine?', img: 'Kidney/C-1.jpg', desc: "Creatinine is a byproduct of protein metabolism, meaning that it's produced in your muscles and then filtered out by the kidneys. It's excreted in your urine. "}, {title: '', img: '', desc: " "}] },
    { key: 'Uric acid', val: { name: "Uric acid", symbol: "mg/dl", value:"5", low: 2.5, high: 6.9 }, info: [{title: 'What\'s Uric acid?', img: 'Kidney/ua-1.jpg', desc: " Uric acid is a byproduct of DNA and cell renewal. It's a waste product that also forms in your body when you digest protein. It's found in many foods, especially meats and fish, but also in some vegetables and grains."}, {title: '', img: '', desc: " "}] },
    { key: 'eGFR', val: { name: "eGFR", symbol: "ml/min", value:"13", low: 60.0, high: 130 }, info: [{title: 'What\'s eGFR?', img: 'Kidney/eGFR-1.jpg', desc: " eGFR, or estimated glomerular filtration rate, is a way of measuring how well your kidneys are filtering waste. It estimates how much blood tiny filters in your kidney called glomeruli can clean every minute based on your body size."}, {title: '', img: '', desc: " "}] },
    { key: 'Alkalini phosphatase', val: { name: "Alkalini phosphatase", symbol: "U/l", value:"94.7", low: 35.0, high: 120.0 }, info: [{title: 'What\'s Alkaline phosphatase?', img: 'Liver/ap-1.jpg', desc: "Alkaline phosphatase (AP) is an enzyme primarily found in the cells of your bones, kidneys, and your liver. It helps form bones and is important for proper growth and development. "}, {title: '', img: '', desc: " "}] },
    { key: 'Total Bilirubin', val: { name: "Total Bilirubin", symbol: "µmol/l", value:"41.54", low: 26.52, high: 106.08 }, info: [{title: 'What\'s Bilirubin?', img: 'Liver/bi-1.jpg', desc: "Bilirubin is a yellow substance that is produced as a byproduct of the breakdown of old red blood. cells. It is converted by your liver and released into blood, bile, urine, or stool. "}, {title: '', img: '', desc: " "}] },
    { key: 'Bilirubin (direct)', val: { name: "Bilirubin (direct)", symbol: "µmol/l", value:"13.26", low: 0, high: 26.52 }, info: [{title: "What's Bilirubin (direct)?", img: 'liver/bi-1.jpg', desc: "Bilirubin is a yellow substance that is produced as a byproduct of the breakdown of old red blood. cells. It is converted by your liver and released into blood, bile, urine, or stool. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Bilirubin (indirect)', val: { name: "Bilirubin (indirect)", symbol: "µmol/l", value:"28.28", low: 0, high: 79.56 }, info: [{title: "What's Bilirubin (indirect)?", img: 'liver/bi-1.jpg', desc: "Bilirubin is a yellow substance that is produced as a byproduct of the breakdown of old red blood. cells. It is converted by your liver and released into blood, bile, urine, or stool. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'GOT (ASAT)', val: { name: "GOT (ASAT)", symbol: "U/l", value:"22.19", low: 10.0, high: 50.0 }, info: [{title: "What's GOT (ASAT)?", img: 'liver/got-1.jpg', desc: " Aspartate Aminotransferase (ASAT) is an enzyme found primarily in your liver, but also in your heart and muscles. It helps to break down amino acids and convert them into energy for your body."}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'GPT (ALAT)', val: { name: "GPT (ALAT)", symbol: "U/l", value:"32.3", low: 10.0, high: 50.0 }, info: [{title: "What's GPT (ALAT) ?", img: 'liver/gpt-1.jpg', desc: "Alanine transaminase (ALT) is an enzyme that helps to break down amino acids, which in turn supply your body with energy. It is found primarily in your liver. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Gamma GT', val: { name: "Gamma GT", symbol: "U/l", value:"16", low: 0, high: 60.0 }, info: [{title: "What's Gamma GT?", img: 'liver/ga-gt-1.jpg', desc: "Gamma-Glutamyl Transpeptidase (GGT) is an enzyme found in your liver. It helps to break down toxins and eliminate them from your body. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Amylase', val: { name: "Amylase", symbol: "g/l", value:"", low: 28.0, high: 100.0 }, info: [{title: "What's Amylase?", img: 'Metabolism/am-1.jpg', desc: "Amylase is a digestive enzyme produced in your pancreas which helps to break down carbohydrates. It's also present in your saliva, where it begins to break down starches before they reach the stomach. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Glucose (NaF)', val: { name: "Glucose (NaF)", symbol: "mmol/l", value:"6.66", low: 0, high: 5.6 }, info: [{title: "What's Glucose (NaF)?", img: 'Metabolism/glu-1.jpg', desc: "Glucose, or blood sugar, is the primary source of energy for your body. It enters your bloodstream after you eat and travels around your body to supply your brain and muscles with fuel. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'HbA1c', val: { name: "HbA1c", symbol: "%", value:"5.8", low: 4.4, high: 5.7 }, info: [{title: "What's HbA1c?", img: 'Metabolism/hbac-1.jpg', desc: "Your HbA1c level shows your average blood sugar level over the last 2 to 3 months. About half of the contribution comes from the last 30 days. It helps indicate your risk for pre-diabetes and diabetes. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'HbA1c (international)', val: { name: "HbA1c (international)", symbol: "mmol/mol", value:"", low: 25.0, high: 39.0 }, info: [{title: "What's HbA1c (international)?", img: 'Metabolism/hbac-1.jpg', desc: " Your HbA1c level shows your average blood sugar level over the last 2 to 3 months. About half of the contribution comes from the last 30 days. It helps indicate your risk for pre-diabetes and diabetes."}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Lipase', val: { name: "Lipase", symbol: "µkat/l", value:"", low: 0, high: 1.0 }, info: [{title: "What's Lipase?", img: 'Metabolism/li-1.jpg', desc: "Lipase is an enzyme or digestive juice that breaks down fat and is primarily found in the cells of your pancreas. It's necessary to help you digest your food. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Calcium', val: { name: "Calcium", symbol: "mmol/l", value:"0.5", low: 2.1, high: 2.55 }, info: [{title: "What's Calcium?", img: 'Minerals/ca-1.jpg', desc: "Calcium is a mineral that is essential for healthy bones, teeth, muscles, and nerves. It also helps with blood clotting. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Potassium', val: { name: "Potassium", symbol: "mmol/l", value:"", low: 3.8, high: 5.2 }, info: [{title: "What's Potassium?", img: 'Minerals/pt-1.jpg', desc: "Potassium is an electrolyte which helps your body regulate fluid levels. It also keeps your muscles and nerves working properly. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Sodium', val: { name: "Sodium", symbol: "mmol/l", value:"", low: 135.0, high: 145.0 }, info: [{title: "What's Sodium?", img: 'Minerals/so-1.jpg', desc: "Sodium is a mineral that helps to keep the right balance of fluids in your body. Your kidneys regulate healthy sodium levels in the blood by removing excess amounts in urine. "}, {title: "What's ?", img: '', desc: " "}] },
    { key: '25-OH Vitamin D', val: {name: '25-OH Vitamin D', symbol: 'ng/ml', value: '9.77', low:20 , high: 40}, info: [{title: "What's 25-OH Vitamin D?", img: '', desc: " "}, {title: "What's ?", img: '', desc: " "}]},
    { key: 'Vitamin B-12', val: {name: 'Vitamin B-12', symbol: 'pg/ml', value: '513', low:211 , high: 911}, info: [{title: "What's Vitamin B-12?", img: '', desc: " "}, {title: "What's ?", img: '', desc: " "}]},
];

export const paget = [
    {key: 'Blood', val: [
        {heading: 'Erythrocytes', unit: 'Tpt/l', value: '', low: 3.9, high: 6.2},
        {heading: 'Hematocrit', unit: '%', value: '47.32', low: 33.0, high: 49.0},
        {heading: 'Hemoglobin', unit: 'g/dl', value: '16.9', low: 12.0, high: 18.0},
        {heading: 'Iron', unit: 'µmol/l', value: '17.30', low: 9.0, high: 31.0 },
        {heading: 'MCH', unit: 'pg', value: '27.9', low: 28.0, high: 33.0},
        {heading: 'MCHC', unit: 'g/dl', value: '31', low: 33.0, high: 36.0},
        {heading: 'MCV', unit: 'fl', value: '90.1', low: 80.0, high: 99.0},
        {heading: 'Thrombocytes', unit: 'gpt/l', value: '', low: 150.0, high: 370.0},
    ],},
    {key: 'Heart', val: [
        {heading: 'Cholestrol', unit: 'mmol/l', value: '14.27', low: 0, high: 5.2},
        {heading: 'HDL cholestrol', unit: 'mmol/l', value: '2.94', low: 1.03, high: 3.3},
        {heading: 'LDH', unit: 'µkat/l', value: '', low: 0, high: 4.13},
        {heading: 'LDL cholestrol', unit: 'mmol/l', value: '10.55', low: 0, high: 4.0},
        {heading: 'LDL/HDL ratio', unit: 'Quotient', value: '3.6', low: 0, high: 3.5},
        {heading: 'Non-HDL cholestrol', unit: 'mmol/l', value: '11.35', low: 0, high: 3.9},
        {heading: 'Triglycerides', unit: 'mmol/l', value: '7.66', low: 0, high: 8.3},
    ],},
    {key: 'Hormones', val: [
        {heading: 'TSH', unit: 'mIU/l', value: '', low: 0.2, high: 5.3},
    ],},
    {key: 'Immunity', val: [
        {heading: 'Basophils', unit: '%', value: '0.5', low: 0.0, high: 1.0},
        {heading: 'Basophils absolute', unit: 'Gpt/l', value: '0.04', low: 0.0, high: 0.2},
        {heading: 'Eosinophils', unit: '%', value: '2.8', low: 2.0, high: 4.0},
        {heading: 'Eosinophils absolute', unit: 'Gpt/l', value: '0.22', low: 0.02, high: 0.75},
        {heading: 'IgG', unit: 'g/l', value: '', low: 5.4, high: 18.22},
        {heading: 'Leukocytes', unit: 'Gpt/l', value: '7.78', low: 3.9, high: 10.2},
        {heading: 'Lymphocytes', unit: '%', value: '40.5', low: 20.0, high: 45.0},
        {heading: 'Lymphocytes absolute', unit: 'Gpt/l', value: '3.15', low: 1.1, high: 4.5},
        {heading: 'Monocytes', unit: '%', value: '3.6', low: 4.0, high: 12.0},
        {heading: 'Monocytes absolute', unit: 'Gpt/l', value: '0.28', low: 0.1, high: 0.9},
        {heading: 'Neutrophils', unit: '%', value: '52.3', low: 42.0, high: 77.0},
        {heading: 'Neutrophils absolute', unit: 'Gpt/l', value: '4.06', low: 1.5, high: 7.7},
        {heading: 'SARS-CoV-2-IgG quant', unit: 'AU/mL', value: '', low: 0.4, high: 250},
        {heading: 'Total protien', unit: 'g/l', value: '73', low: 60.0, high: 80.0},
        {heading: "Apolipoprotien - A1 (APO-A1)", unit: "mg/dl", value:"122", low: 86.0, high: 152.0},
        {heading: "Apolipoprotien - B (APO-B)", unit: "mg/dl", value:"102", low: 56.0, high: 145.0},
        {heading: "APO B / APO A1 Ratio (APO B/A1)", unit: "Ratio", value:"0.8", low: 0.40, high: 1.26},
    ],},
    {key: 'Kidneys', val: [
        {heading: 'Creatinine', unit: 'mg/dl', value: '0.76', low: 0, high: 1.16},
        {heading: 'Uric acid', unit: 'mg/dl', value: '5', low: 2.5, high: 6.9},
        {heading: 'eGFR', unit: 'ml/min', value: '132', low: 60.0, high: 130},
    ],},
    {key: 'Liver', val: [
        {heading: 'Alkalini phosphatase', unit: 'U/l', value: '94.7', low: 35.0, high: 120.0},
        {heading: 'Total Bilirubin', unit: 'µmol/l', value: '41.54', low: 26.52, high: 106.08},
        {heading: 'Bilirubin (direct)', unit: 'µmol/l', value: '13.26', low: 0, high: 26.52 },
        {heading: 'Bilirubin (indirect)', unit: 'µmol/l', value: '28.28', low: 0, high: 79.56},
        {heading: 'GOT (ASAT)', unit: 'U/l', value: '22.19', low: 10.0, high: 50.0 },
        {heading: 'GPT (ALAT)', unit: 'U/l', value: '32.3', low: 10.0, high: 50.0 },
        {heading: 'Gamma GT', unit: 'U/l', value: '16', low: 0, high: 60.0},
        {heading: 'Total protien', unit: 'g/l', value: '7.3', low: 60.0, high: 80.0},
    ],},
    {key: 'Metabolism', val: [
        {heading: 'Amylase', unit: 'U/l', value: '', low: 28.0, high: 100.0 },
        {heading: 'Total Bilirubin', unit: 'µmol/l', value: '41.54', low: 26.52, high: 106.08},
        {heading: 'Bilirubin (direct)', unit: 'µmol/l', value: '13.26', low: 0, high: 26.52 },
        {heading: 'Bilirubin (indirect)', unit: 'µmol/l', value: '28.28', low: 0, high: 79.56},
        {heading: 'Glucose (NaF)', unit: 'mmol/l', value: '6.66', low: 0, high: 5.6 },
        {heading: 'HbA1c', unit: '%', value: '5.8', low: 4.4, high: 5.7},
        {heading: 'HbA1c (international)', unit: 'mmol/mol', value: '', low: 25.0, high: 39.0},
        {heading: 'Lipase', unit: 'µkat/l', value: '', low: 0, high: 1.0 },
        {heading: 'TSH', unit: 'mIU/l', value: '1.39', low: 0.2, high: 5.3 },
        {heading: 'Uric acid', unit: 'mg/dl', value: '5', low: 2.5, high: 6.9},
    ],},
    {key: 'Minerals', val: [
        {heading: 'Calcium', unit: 'mmol/l', value: '9.58', low: 2.1, high: 2.55},
        {heading: 'Iron', unit: 'µmol/l', value: '17.30', low: 9.0, high: 31.0 },
        {heading: 'Potassium', unit: 'mmol/l', value: '', low: 3.8, high: 5.2},
        {heading: 'Sodium', unit: 'mmol/l', value: '', low: 135.0, high: 145.0},
    ],},
    {key: 'Vitamins', val: [
        {heading: '25-OH Vitamin D', unit: 'ng/ml', value: '9.77', low: 20, high: 40},
        {heading: 'Vitamin B-12', unit: 'pg/ml', value: '521', low: 211, high: 911},
    ],},
];

export const cardata =  [
    {key: "Blood", val: {title: "Blood", img: "main-blood.jpg", desc: "Your blood is a Key part of your body's circulatory system. it helps your body dunction properly by carrying oxygen and nutrients and removing waste products. it's made up of red blood cells , white blood cells, platelets, and plasma."},},
    {key: "Heart", val: {title: "Heart", img: "main-heart.jpg", desc: "Your heart is the master pump of the body, supplying oxygen and nutrients to every cell. The fist-sized powerhouse of the cardiovascular system beats 100,000 times and pumps 7,000 liters of blood each day."},},
    {key: "Hormones", val: {title: "Hormones", img: "main-hormones.jpg", desc: "Your hormones are powerful chemical messengers of your endocrine system that influence everything from mood, energy levels, and hunger to metabolism and sexual development. They also help fight off infections."},},
    {key: "Immunity", val: {title: "Immunity", img: "main-immunity.jpg", desc: "Your immune system is a complex network of organs, cells, and proteins. As your personal protector, it defends your body against germs and other invaders. Symptoms like fever and inflammation are signs that it's doing its job."},},
    {key: "Kidneys", val: {title: "Kidneys", img: "main-kidneys.jpg", desc: "Your kidneys are bean-shaped organs at the back of your torso, about the size of a fist. As part of your urinary system, their main function is to filter your blood, remove waste, and balance your body's fluids."},},
    {key: "Liver", val: {title: "Liver", img: "main-liver.jpg", desc: "Your liver is a real multitasker. The size of an American football, it sits under your ribs on your right side, where it performs over 500 important jobs. It's essential for digesting food and ridding your body of toxins."},},
    {key: "Metabolism", val: {title: "Metabolism", img: "main-metabolism.jpg", desc: "Metabolism is your body's natural process of breaking down food and converting it to energy. This process allows you to grow and repair your muscles, make hormones, and keep your body running smoothly."},},
    {key: "Minerals", val: {title: "Minerals", img: "main-minerals.jpg", desc: "Minerals are essential for your body and help with the growth, development, and maintenance of bones, teeth, muscles, and nerves. They are needed in small amounts and can be found in foods and drinks."},},
    {key: "Vitamins", val: {title: "Vitamins", img: "main-vitamins.jpg", desc: "Vitamins are micronutrients that are important for good health. Your body needs 13 different kinds every day. Some help your body absord other nutrients better, some boost your energy levels, and others keep your skin looking fresh."},},
];

export const articles = [
    { key: 'Erythrocytes', info: [{title: 'Nutrition', img: 'article.png', desc: 'Low erythrocyte levels? The best diet plan for'}, {title: 'Did you know?', img: '', desc: " "}] },
    { key: 'Hematocrit',  info: [{title: 'Nutrition', img: 'article.png', desc: 'Low erythrocyte levels? The best diet plan for'}, {title: 'Did you know?', img: '', desc: " "}] },
    { key: 'Hemoglobin',  info: [{title: 'Nutrition', img: 'article.png', desc: 'Low erythrocyte levels? The best diet plan for'}, {title: 'Did you know?', img: '', desc: " "}] },
    { key: 'Iron',  info: [{title: 'Nutrition', img: 'article.png', desc: 'Low erythrocyte levels? The best diet plan for'}, {title: 'Did you know?', img: '', desc: " "}] },
    { key: 'MCH',  info: [{title: 'Nutrition', img: 'article.png', desc: 'Low erythrocyte levels? The best diet plan for'}, {title: 'Did you know?', img: '', desc: " "}] },
    { key: 'MCHC',  info: [{title: 'Nutrition', img: 'article.png', desc: 'Low erythrocyte levels? The best diet plan for'}, {title: 'Did you know?', img: '', desc: " "}] },
    { key: 'MCV',  info: [{title: 'Nutrition', img: 'article.png', desc: 'Low erythrocyte levels? The best diet plan for'}, {title: 'Did you know?', img: '', desc: " "}] },
    { key: 'Thrombocytes',  info: [{title: 'Nutrition', img: 'article.png', desc: 'TLow erythrocyte levels? The best diet plan for'}, {title: 'Did you know?', img: '', desc: " "}] },
    { key: 'Cholestrol',  info: [{title: 'Nutrition', img: 'article.png', desc: 'Low erythrocyte levels? The best diet plan for'}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'HDL cholestrol', info: [{title: 'Nutrition', img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'LDH', info: [{title: 'Nutrition', img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'LDL cholestrol',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'LDL HDL ratio',  info: [{title: 'Nutrition', img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Non-HDL cholestrol',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Triglycerides',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {img: '', desc: " "}] },
    { key: 'TSH',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Basophils',  info: [{title: 'Nutrition', img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Basophils absolute',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Eosinophils',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Eosinophils absolute',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'IgG',  info: [{title: 'Nutrition', img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Leukocytes',  info: [{title: 'Nutrition', img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Lymphocytes',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Lymphocytes absolute',  info: [{title: 'Nutrition', img: 'Iarticle.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Monocytes',  info: [{title: 'Nutrition', img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Monocytes absolute',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Neutrophils',  info: [{title: 'Nutrition', img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Neutrophils absolute',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'SARS-CoV-2-IgG quant',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Total protien',  info: [{title: 'Nutrition', img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Apolipoprotien-A1(APO-A1)', info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's Apolipoprotien - A1 (APO-A1)?", img: '', desc: " "}] },
    { key: 'Apolipoprotien-B(APO-B)', info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's Apolipoprotien - B (APO-B)?", img: '', desc: " "}] },
    { key: 'APO B APO A1 Ratio (APO B A1)', info: [{title: "Nutrition", img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Creatinine', info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Uric acid',  info: [{title: "Nutrition", img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'eGFR',  info: [{title: "Nutrition", img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Alkalini phosphatase',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Total Bilirubin',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Bilirubin (direct)',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Bilirubin (indirect)',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'GOT (ASAT)',  info: [{title: "Nutrition", img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'GPT (ALAT)',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Gamma GT',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Amylase',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Glucose (NaF)',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'HbA1c',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'HbA1c (international)',  info: [{title: "Nutrition", img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Lipase',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Calcium',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Potassium',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: 'Sodium',info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}] },
    { key: '25-OH Vitamin D',  info: [{title: "Nutrition", img: 'article.png', desc: "Low erythrocyte levels? The best diet plan for "}, {title: "What's ?", img: '', desc: " "}]},
    { key: 'Vitamin B-12',  info: [{title: "Nutrition", img: 'article.png', desc: " Low erythrocyte levels? The best diet plan for"}, {title: "What's ?", img: '', desc: " "}]},
];